env:
  global:
    - CUDA_VERSION="10.0"
    - CUDA_PKG_VERSION="130-1"
    - CUDA_PKG=cuda-repo-ubuntu1404_${CUDA_VERSION}.${CUDA_PKG_VERSION}_amd64.deb
    - CUDA_LIB_LOCAL=${HOME}/cuda_lib_${CUDA_VERSION}
    - CUDA_HOME=${CUDA_LIB_LOCAL}

install:
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/${CUDA_PKG}
  - sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/7fa2af80.pub
  - sudo dpkg -i ${CUDA_PKG}
  - rm ${CUDA_PKG}
  - sudo apt-get -y update
  - sudo apt-get install -y --no-install-recommends  cuda-core-${CUDA_VERSION}  cuda-cudart-dev-${CUDA_VERSION}  cuda-cublas-dev-${CUDA_VERSION} cuda-curand-dev-${CUDA_VERSION}
  - mkdir -p ${CUDA_LIB_LOCAL}
  - sudo cp -rL /usr/local/cuda-${CUDA_VERSION}/bin /usr/local/cuda-${CUDA_VERSION}/lib64 /usr/local/cuda-${CUDA_VERSION}/include /usr/local/cuda-${CUDA_VERSION}/nvvm ${CUDA_LIB_LOCAL}

script:
  - make
  - make gpu_awk

after_script:
  - make clean
